### ISSUE TITLE
返回的中文乱码

### ISSUE THREAD

**Issue by hardywen** [z-song/lumen-swoole#10]
发现一个小问题

用ajax请求，返回json格式的话，中文没问题。

但是直接浏览器打开接口，中文就乱码了。

对比了一下 php-fpm 的返回头部是这样的: `Content-Type:text/html; charset=UTF-8`

而用了这个组件的头部是：`Content-Type:text/html`
少了 charset=UTF-8

能在response的header加上这个吗

**Comment by z-song** [comment]
输出非json格式的中文，用浏览器打开就会显示乱码？

**Comment by z-song** [comment]
已经修复了

response在被send之前需要调用`Symfony\Component\HttpFoundation\Response::prepare()`方法

**Comment by z-song** [comment]
谢谢反馈！
